
# 工作目录
[general]
working_directory = "~/"
# 导入颜色方案
import = ["./gruvbox_dark.toml"]

# Shell
#[terminal]
#shell = { program = "/bin/zsh" }

# 字体设置（macOS 通常字体偏小）
[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }
size = 20.0

# 窗口配置
[window]
opacity = 0.9
padding = { x = 10, y = 5 }
decorations = "transparent"
startup_mode = "Maximized"

# 环境变量
[env]
TERM = "xterm-256color"

# 快捷键（macOS 用 Command 复制粘贴）
[keyboard]
bindings = [
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" }
]
