#!/usr/bin/env bash
# Detect OS and redirect

case "$(uname -s)" in
    Linux*|Darwin*)
        exec "$HOME/.config/helix/wezilix.sh" "$@"
        ;;
    *)
        # Windows (msys / cygwin / powershell)
        exec pwsh -NoProfile -File "$env:$USER/Users/AppData/Roaming/helix/wezilix.ps1" $args
        ;;
esac
