FROM fedora:43

RUN dnf install -y \
    python3 \
    python3-pip \
    python3-virtualenv \
    git \
    gcc \
    && dnf clean all

WORKDIR /workspace

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
